version: '3.8'

services:
  bot:
    build: .
    container_name: grammy-bot
    restart: unless-stopped
    ports:
      - "${HTTP_SERVER_PORT:-3002}:3002"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
      - BOT_MODE=${BOT_MODE:-polling}
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017/grammy-bot
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:alpine
    container_name: grammy-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:latest
    container_name: grammy-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data: